/**
 * Python emitter for the SDK generator (DX02).
 *
 *   packages/python-client/soroban_explorer/_operations.py  OPERATIONS table
 *   packages/python-client/soroban_explorer/models.py       TypedDict models
 *
 * Output is plain Python 3.9+ with only stdlib `typing`; `object` stands in
 * for unrepresentable schemas (never `Any`).
 */
import type { JsonSchema, OpenApiDocument } from '../../src/lib/openapi/normalize';
import type { Emitter } from './emitters';
import { modelName } from './emit-typescript';

const HEADER = `# AUTO-GENERATED by \`npm run sdk:generate\` from the OpenAPI spec served at
# /api/v1/openapi.json. DO NOT EDIT: CI regenerates this file and fails on drift.
`;

/** Serialize a JSON value as a Python literal. */
export function toPy(value: unknown, indent = ''): string {
  if (value === null || value === undefined) return 'None';
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '()';
    return `(${value.map((v) => toPy(v, indent)).join(', ')},)`;
  }
  const entries = Object.entries(value as Record<string, unknown>).filter(
    ([, v]) => v !== undefined,
  );
  if (entries.length === 0) return '{}';
  const inner = `${indent}    `;
  return `{\n${entries.map(([k, v]) => `${inner}${JSON.stringify(k)}: ${toPy(v, inner)},`).join('\n')}\n${indent}}`;
}

function pyType(schema: JsonSchema | null | undefined, known: Set<string>, depth = 0): string {
  if (!schema || depth > 5) return 'object';
  let t: string;
  if (typeof schema.$ref === 'string') {
    const m = /^#\/components\/schemas\/(.+)$/.exec(schema.$ref);
    t = m && known.has(m[1]) ? `"${modelName(m[1])}"` : 'object';
  } else if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    const lits = schema.enum.filter(
      (v) => typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean',
    );
    t = lits.length > 0 ? `Literal[${lits.map((v) => toPy(v)).join(', ')}]` : 'object';
  } else if (schema.oneOf || schema.anyOf) {
    const parts = (schema.oneOf ?? schema.anyOf ?? []).map((s) => pyType(s, known, depth + 1));
    t =
      parts.length > 1 ? `Union[${Array.from(new Set(parts)).join(', ')}]` : (parts[0] ?? 'object');
  } else if (schema.allOf) {
    t = schema.allOf.length === 1 ? pyType(schema.allOf[0], known, depth + 1) : 'Dict[str, object]';
  } else {
    const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
    switch (type) {
      case 'string':
        t = 'str';
        break;
      case 'integer':
        t = 'int';
        break;
      case 'number':
        t = 'float';
        break;
      case 'boolean':
        t = 'bool';
        break;
      case 'array':
        t = `List[${pyType(schema.items, known, depth + 1)}]`;
        break;
      case 'object':
        t = 'Dict[str, object]';
        break;
      default:
        t = schema.properties ? 'Dict[str, object]' : 'object';
    }
  }
  return schema.nullable === true && t !== 'object' ? `Optional[${t}]` : t;
}

export function emitPythonModels(doc: OpenApiDocument): string {
  const schemas = doc.components?.schemas ?? {};
  const known = new Set(Object.keys(schemas));
  const blocks = Object.keys(schemas)
    .sort()
    .map((raw) => {
      const name = modelName(raw);
      const s = schemas[raw];
      if (s.properties && Object.keys(s.properties).length > 0) {
        const fields = Object.keys(s.properties)
          .sort()
          .map((k) => `        ${JSON.stringify(k)}: ${pyType(s.properties![k], known)},`);
        return `${name} = TypedDict(\n    ${JSON.stringify(name)},\n    {\n${fields.join('\n')}\n    },\n    total=False,\n)`;
      }
      return `${name} = ${pyType({ ...s, nullable: false }, known)}`;
    });
  return `${HEADER}"""Typed models for API payloads (TypedDicts; all keys optional)."""

from typing import Dict, List, Literal, Optional, TypedDict, Union

__all__ = [${Object.keys(schemas)
    .sort()
    .map((n) => JSON.stringify(modelName(n)))
    .join(', ')}]

${blocks.join('\n\n')}
`;
}

export const pythonEmitter: Emitter = ({ doc, ops, fingerprint }) => {
  const table: Record<string, unknown> = {};
  for (const op of ops) {
    table[op.id] = {
      method: op.method.toUpperCase(),
      path: op.path,
      path_params: op.params.filter((p) => p.in === 'path').map((p) => p.name),
      query: op.params
        .filter((p) => p.in === 'query')
        .map((p) => ({
          name: p.name,
          type: p.type,
          required: p.required,
          item_type: p.itemType,
          enum: p.enum && p.enum.length > 0 ? p.enum : undefined,
          minimum: p.minimum,
          maximum: p.maximum,
        })),
      body: op.body ? (op.body.required ? 'required' : 'optional') : 'none',
      content_type: op.body?.contentType,
      deprecated: op.deprecated,
      summary: op.summary,
    };
  }
  const operations = `${HEADER}"""Operation table for every operation in the OpenAPI spec."""

from typing import Dict

SPEC_VERSION = ${toPy(doc.info?.version ?? '0.0.0')}
SPEC_FINGERPRINT = ${toPy(fingerprint)}
OPERATION_COUNT = ${ops.length}

OPERATIONS: Dict[str, Dict[str, object]] = ${toPy(table)}
`;
  return [
    { path: 'packages/python-client/soroban_explorer/_operations.py', content: operations },
    { path: 'packages/python-client/soroban_explorer/models.py', content: emitPythonModels(doc) },
  ];
};
