/**
 * TypeScript emitter for the SDK generator (DX01).
 *
 * Emits, from the normalized OpenAPI operations:
 *   - models.ts      — one exported type per `components.schemas` entry;
 *   - operations.ts  — runtime operation metadata (`OPERATIONS`) used for
 *                      request building and runtime param validation, plus
 *                      the compile-time `OperationTypes` map (path, query,
 *                      body and response types per operation).
 *
 * Generated code contains no `any`: unrepresentable schemas become `unknown`.
 */
import type {
  JsonSchema,
  NormalizedOperation,
  NormalizedParam,
  OpenApiDocument,
} from '../../src/lib/openapi/normalize';

const HEADER = `// AUTO-GENERATED by \`npm run sdk:generate\` from the OpenAPI spec served at
// /api/v1/openapi.json. DO NOT EDIT: CI regenerates this file and fails on drift.
`;

const MAX_DEPTH = 6;

/**
 * Component names that actually exist. The spec contains `$ref`s to schemas
 * that were never declared; those become `unknown` instead of dangling types.
 */
let knownModels = new Set<string>();

export function setKnownModels(doc: OpenApiDocument): void {
  knownModels = new Set(Object.keys(doc.components?.schemas ?? {}));
}
const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function modelName(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[0-9]/.test(cleaned) ? `M_${cleaned}` : cleaned;
}

function propKey(key: string): string {
  return IDENT.test(key) ? key : JSON.stringify(key);
}

function literal(v: unknown): string | null {
  if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
    return JSON.stringify(v);
  }
  if (v === null) return 'null';
  return null;
}

/** JSON Schema → TypeScript type expression. `modelPrefix` qualifies $refs. */
export function schemaToTs(
  schema: JsonSchema | null | undefined,
  modelPrefix: string,
  depth = 0,
  indent = '',
): string {
  if (!schema || depth > MAX_DEPTH) return 'unknown';
  let out: string;
  if (typeof schema.$ref === 'string') {
    const m = /^#\/components\/schemas\/(.+)$/.exec(schema.$ref);
    out = m && knownModels.has(m[1]) ? `${modelPrefix}${modelName(m[1])}` : 'unknown';
  } else if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    const lits = schema.enum.map(literal).filter((l): l is string => l !== null);
    out = lits.length > 0 ? Array.from(new Set(lits)).join(' | ') : 'unknown';
  } else if (schema.oneOf || schema.anyOf) {
    const variants = (schema.oneOf ?? schema.anyOf ?? []).map((s) =>
      schemaToTs(s, modelPrefix, depth + 1, indent),
    );
    out = variants.length > 0 ? variants.map((v) => `(${v})`).join(' | ') : 'unknown';
  } else if (schema.allOf) {
    const parts = schema.allOf.map((s) => schemaToTs(s, modelPrefix, depth + 1, indent));
    out = parts.length > 0 ? parts.map((v) => `(${v})`).join(' & ') : 'unknown';
  } else {
    const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
    switch (type) {
      case 'string':
        out = 'string';
        break;
      case 'integer':
      case 'number':
        out = 'number';
        break;
      case 'boolean':
        out = 'boolean';
        break;
      case 'array':
        out = `Array<${schemaToTs(schema.items, modelPrefix, depth + 1, indent)}>`;
        break;
      case 'object':
      case undefined:
        if (schema.properties && Object.keys(schema.properties).length > 0) {
          const required = new Set(schema.required ?? []);
          const inner = `${indent}  `;
          const lines = Object.keys(schema.properties)
            .sort()
            .map((key) => {
              const prop = schema.properties![key];
              const doc =
                typeof prop.description === 'string' && prop.description.trim()
                  ? `${inner}/** ${prop.description.trim().replace(/\*\//g, '* /').replace(/\s+/g, ' ')} */\n`
                  : '';
              const opt = required.has(key) ? '' : '?';
              return `${doc}${inner}${propKey(key)}${opt}: ${schemaToTs(prop, modelPrefix, depth + 1, inner)};`;
            });
          if (schema.additionalProperties) lines.push(`${inner}[key: string]: unknown;`);
          out = `{\n${lines.join('\n')}\n${indent}}`;
        } else if (type === 'object' || schema.additionalProperties) {
          const ap = schema.additionalProperties;
          out =
            typeof ap === 'object' && ap !== null
              ? `Record<string, ${schemaToTs(ap, modelPrefix, depth + 1, indent)}>`
              : 'Record<string, unknown>';
        } else {
          out = 'unknown';
        }
        break;
      default:
        out = 'unknown';
    }
  }
  return schema.nullable === true && out !== 'unknown' ? `${out} | null` : out;
}

export function emitModels(doc: OpenApiDocument): string {
  setKnownModels(doc);
  const schemas = doc.components?.schemas ?? {};
  const blocks = Object.keys(schemas)
    .sort()
    .map((name) => {
      const s = schemas[name];
      const doc =
        typeof s.description === 'string' && s.description.trim()
          ? `/** ${s.description.trim().replace(/\*\//g, '* /').replace(/\s+/g, ' ')} */\n`
          : '';
      return `${doc}export type ${modelName(name)} = ${schemaToTs(s, '', 0, '')};`;
    });
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}

function paramTs(p: NormalizedParam): string {
  if (p.enum && p.enum.length > 0) return p.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (p.type) {
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return p.itemType === 'integer' || p.itemType === 'number'
        ? 'Array<number>'
        : p.itemType === 'boolean'
          ? 'Array<boolean>'
          : 'Array<string>';
    default:
      return 'string';
  }
}

function objectType(params: NormalizedParam[], indent: string): string {
  if (params.length === 0) return 'Record<string, never>';
  const lines = params.map((p) => {
    const doc = p.description
      ? `${indent}  /** ${p.description.replace(/\*\//g, '* /').replace(/\s+/g, ' ')} */\n`
      : '';
    return `${doc}${indent}  ${propKey(p.name)}${p.required ? '' : '?'}: ${paramTs(p)};`;
  });
  return `{\n${lines.join('\n')}\n${indent}}`;
}

export function successResponse(op: NormalizedOperation): JsonSchema | null | 'void' {
  const ok = op.responses.filter((r) => /^2\d\d$/.test(r.status));
  const withSchema = ok.find((r) => r.schema);
  if (withSchema) return withSchema.schema;
  if (ok.length > 0 && ok.every((r) => r.status === '204')) return 'void';
  return null;
}

export function emitOperations(
  doc: OpenApiDocument,
  ops: NormalizedOperation[],
  fingerprint: string,
): string {
  setKnownModels(doc);
  const meta = ops.map((op) => {
    const query = op.params
      .filter((p) => p.in === 'query')
      .map((p) => {
        const fields = [
          `name: ${JSON.stringify(p.name)}`,
          `type: '${p.type}'`,
          `required: ${p.required}`,
        ];
        if (p.itemType) fields.push(`itemType: '${p.itemType}'`);
        if (p.enum && p.enum.length > 0) fields.push(`enum: ${JSON.stringify(p.enum)}`);
        if (p.minimum !== undefined) fields.push(`minimum: ${p.minimum}`);
        if (p.maximum !== undefined) fields.push(`maximum: ${p.maximum}`);
        return `{ ${fields.join(', ')} }`;
      });
    const pathParams = op.params.filter((p) => p.in === 'path').map((p) => JSON.stringify(p.name));
    const body = op.body ? (op.body.required ? 'required' : 'optional') : 'none';
    const lines = [
      `    method: '${op.method.toUpperCase()}',`,
      `    path: ${JSON.stringify(op.path)},`,
      `    pathParams: [${pathParams.join(', ')}],`,
      `    query: [${query.length ? `\n      ${query.join(',\n      ')},\n    ` : ''}],`,
      `    body: '${body}',`,
    ];
    if (op.body) lines.push(`    contentType: ${JSON.stringify(op.body.contentType)},`);
    lines.push(
      `    deprecated: ${op.deprecated},`,
      `    tags: ${JSON.stringify(op.tags)},`,
      `    summary: ${JSON.stringify(op.summary)},`,
    );
    return `  ${op.id}: {\n${lines.join('\n')}\n  },`;
  });

  const types = ops.map((op) => {
    const pathParams = op.params.filter((p) => p.in === 'path');
    const query = op.params.filter((p) => p.in === 'query');
    const res = successResponse(op);
    const response =
      res === 'void' ? 'void' : res === null ? 'unknown' : schemaToTs(res, 'Models.', 0, '    ');
    const body = op.body
      ? op.body.contentType === 'application/json'
        ? schemaToTs(op.body.schema, 'Models.', 0, '    ')
        : 'string'
      : 'never';
    const summary = op.summary
      ? `  /** ${op.method.toUpperCase()} ${op.path} — ${op.summary.replace(/\*\//g, '* /').replace(/\s+/g, ' ')} */\n`
      : `  /** ${op.method.toUpperCase()} ${op.path} */\n`;
    const dep = op.deprecated ? '  /** @deprecated */\n' : '';
    return `${summary}${dep}  ${op.id}: {\n    path: ${objectType(pathParams, '    ')};\n    query: ${objectType(query, '    ')};\n    body: ${body};\n    response: ${response};\n  };`;
  });

  // Precomputed call parameter shapes: `client.call(id, params)` indexes this
  // interface directly (no conditional types, which blow TS's union limits
  // across hundreds of operations).
  const params = ops.map((op) => {
    const pathReq = op.params.some((p) => p.in === 'path');
    const queryReq = op.params.some((p) => p.in === 'query' && p.required);
    const fields = [
      op.params.some((p) => p.in === 'path')
        ? `path${pathReq ? '' : '?'}: OperationTypes['${op.id}']['path'];`
        : 'path?: Record<string, never>;',
      op.params.some((p) => p.in === 'query')
        ? `query${queryReq ? '' : '?'}: OperationTypes['${op.id}']['query'];`
        : 'query?: Record<string, never>;',
      op.body
        ? `body${op.body.required ? '' : '?'}: OperationTypes['${op.id}']['body'];`
        : 'body?: never;',
      'signal?: AbortSignal;',
      'headers?: Record<string, string>;',
    ];
    return `  ${op.id}: { ${fields.join(' ')} };`;
  });

  const usesModels = types.some((t) => t.includes('Models.'));
  return `${HEADER}${usesModels ? "import type * as Models from './models';\n" : ''}
export const SPEC_VERSION = ${JSON.stringify(doc.info?.version ?? '0.0.0')} as const;
/** SHA-256 (first 16 hex chars) of the normalized API surface this file was generated from. */
export const SPEC_FINGERPRINT = ${JSON.stringify(fingerprint)} as const;

export type ParamType = 'string' | 'integer' | 'number' | 'boolean' | 'array' | 'object';

export interface QueryParamSpec {
  readonly name: string;
  readonly type: ParamType;
  readonly required: boolean;
  readonly itemType?: ParamType;
  readonly enum?: ReadonlyArray<string | number>;
  readonly minimum?: number;
  readonly maximum?: number;
}

export interface OperationSpec {
  readonly method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  readonly path: string;
  readonly pathParams: ReadonlyArray<string>;
  readonly query: ReadonlyArray<QueryParamSpec>;
  readonly body: 'none' | 'optional' | 'required';
  readonly contentType?: string;
  readonly deprecated: boolean;
  readonly tags: ReadonlyArray<string>;
  readonly summary: string;
}

export const OPERATIONS = {
${meta.join('\n')}
} as const satisfies Record<string, OperationSpec>;

export type OperationId = keyof typeof OPERATIONS;

export const OPERATION_COUNT = ${ops.length} as const;

export interface OperationTypes {
${types.join('\n')}
}

export interface OperationParams {
${params.join('\n')}
}
`;
}
