/**
 * Route parity matrix (docs/sdk/parity-matrix.md).
 *
 * Every operation in the OpenAPI spec is listed with how each first-party
 * client exposes it. Generated clients cover every operation by construction
 * (`client.call(id, …)`); curated ergonomic methods are listed where they
 * exist. The matrix is regenerated with the clients, so CI drift checks keep
 * it truthful.
 */
import type { NormalizedOperation } from '../../src/lib/openapi/normalize';

/** Curated TypeScript convenience methods (packages/client/src/resources.ts). */
export const TS_ERGONOMIC: Record<string, string> = {
  getTransactions: 'client.transactions.list()',
  getTransactionsByHash: 'client.transactions.get(hash)',
  getEvents: 'client.events.list()',
  getContracts: 'client.contracts.list()',
  getEventsById: 'client.events.get(id)',
  getContractsByAddress: 'client.contracts.get(address)',
  getTokens: 'client.tokens.list()',
  getTokensByAddress: 'client.tokens.get(address)',
  getWalletsByAddressTransactions: 'client.wallets.transactions(address)',
  getWalletsByAddressEvents: 'client.wallets.events(address)',
  getNetwork: 'client.network.status()',
  getSearchSuggest: 'client.search.suggest(q)',
};

/** Curated Python convenience methods (packages/python-client). */
export const PY_ERGONOMIC: Record<string, string> = {
  getTransactions: 'client.transactions.list()',
  getTransactionsByHash: 'client.transactions.get(hash)',
  getEvents: 'client.events.list()',
  getContracts: 'client.contracts.list()',
  getEventsById: 'client.events.get(id)',
  getContractsByAddress: 'client.contracts.get(address)',
  getTokens: 'client.tokens.list()',
  getTokensByAddress: 'client.tokens.get(address)',
  getWalletsByAddressTransactions: 'client.wallets.transactions(address)',
  getWalletsByAddressEvents: 'client.wallets.events(address)',
  getNetwork: 'client.network.status()',
};

export function emitParityMatrix(
  ops: NormalizedOperation[],
  files: Array<{ path: string }>,
): string {
  const hasPython = files.some((f) => f.path.startsWith('packages/python-client/'));
  const rows = [...ops]
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
    .map((op) => {
      const ts = TS_ERGONOMIC[op.id] ? `✅ \`${TS_ERGONOMIC[op.id]}\`` : '✅ `call`';
      const py = hasPython
        ? ` ${PY_ERGONOMIC[op.id] ? `✅ \`${PY_ERGONOMIC[op.id]}\`` : '✅ `call`'} |`
        : '';
      const dep = op.deprecated ? ' ⚠️ deprecated' : '';
      return `| \`${op.id}\` | ${op.method.toUpperCase()} | \`${op.path}\`${dep} | ${ts} |${py}`;
    });
  const pyHead = hasPython ? ' Python |' : '';
  const pySep = hasPython ? '--------|' : '';
  return `<!-- AUTO-GENERATED by \`npm run sdk:generate\`. DO NOT EDIT. -->

# SDK Route Parity Matrix

Every operation in \`/api/v1/openapi.json\` (${ops.length} operations) and how each
first-party client exposes it. "\`call\`" means the generated, fully typed
\`client.call('<operationId>', …)\`; named methods are curated conveniences over
the same call.

Realtime surfaces (not in OpenAPI): feed WebSocket \`/ws/v1/feed\`, feed SSE
\`/api/v1/feed/sse\` and GraphQL subscriptions (SSE on \`/api/graphql\`) are covered
by \`client.realtime\` in TypeScript${hasPython ? ' and `client.stream_feed()` in Python' : ''}.

| Operation | Method | Path | TypeScript |${pyHead}
|-----------|--------|------|------------|${pySep}
${rows.join('\n')}
`;
}
