-- SR01 — Full-text search over contracts, decoded events and transaction
-- metadata (docs/search-design.md §2.2).
--
-- The unified inverted index lives in `_search_documents`. `search_vector` is a
-- Postgres generated column so it can never drift out of sync with `content`;
-- the GIN index on it backs ranked full-text queries and the trigram GIN index
-- backs typo-tolerant matching. This table is maintained incrementally by the
-- indexer and can be rebuilt from primary tables.
--
-- NOTE: `search_vector` is modelled as `Unsupported("tsvector")` in
-- prisma/schema.prisma because it is generated by the database. Do not
-- regenerate this migration with `prisma migrate dev` — it would drop the
-- GENERATED expression and the tsvector GIN index.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE "_search_documents" (
    "id" TEXT NOT NULL,
    "doc_type" TEXT NOT NULL,
    "doc_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "metadata" JSONB,
    "search_vector" tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, "content")) STORED,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "_search_documents_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "_search_documents_doc_type_doc_id_key" ON "_search_documents"("doc_type", "doc_id");

CREATE INDEX "_search_documents_doc_type_idx" ON "_search_documents"("doc_type");

CREATE INDEX "_search_documents_search_vector_idx" ON "_search_documents" USING GIN ("search_vector");

CREATE INDEX "_search_documents_content_trgm_idx" ON "_search_documents" USING GIN ("content" gin_trgm_ops);
