import { NetworkName, NetworkProfile } from '../profiles';
import { ApiKeyContext } from '../middleware/apiKeyAuth';
import { SessionContext } from '../middleware/cookieAuth';
import { TokenBucketResult } from '../middleware/tokenBucket';
import { Role, Tier } from '../auth/rbac';
import { SupportedLanguage } from '../i18n/engine';

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      coldStorage?: {
        enabled: boolean;
        type: string;
        path?: string;
        ledgerSeq: number;
      };
      network?: NetworkName;
      networkProfile?: NetworkProfile;
      /** Unique ID for this HTTP request (correlation). */
      requestId?: string;
      startedAt?: number;
      apiKey?: ApiKeyContext;
      /** Session data from validated session cookie (cookieAuth middleware). */
      session?: SessionContext;
      rateLimitResult?: TokenBucketResult;
      user?: {
        id: string;
        address: string;
        role: Role;
        tier: Tier;
        sessionId: string;
        appId?: string;
      };
      /** OpenTelemetry / B3 trace ID propagated from upstream or generated by OTel. */
      traceId?: string;
      /** OpenTelemetry / B3 span ID of the root server span. */
      spanId?: string;
      /** Admin actor identity set by adminAuth middleware (freeze, audit routes). */
      actor?: string;
      /** Data-sovereignty scope from the `?region=` query param, set by regionScope middleware. */
      regionScope?: 'us' | 'eu' | 'apac' | 'sa' | 'af';
      /** i18n resolved locale */
      locale?: SupportedLanguage;
      /** i18n bound sync translator */
      t?: (key: string, values?: Record<string, unknown>) => string;
      /** i18n bound async translator */
      tAsync?: (key: string, values?: Record<string, unknown>) => Promise<string>;
    }
  }
}
