import crypto from 'crypto';
import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { Prisma } from '@prisma/client';
import { prismaWrite as prisma, prismaRead } from '../db';
import { asyncHandler } from '../middleware/asyncHandler';
import { apiKeyAuth, requireApiKey } from '../middleware/apiKeyAuth';
import { assertSafeUrl, safePost, SsrfBlockedError } from '../webhooks/ssrf-guard';
import { uuidv7 } from '../utils/uuidv7';
import { sensitiveReadLog } from '../middleware/sensitiveReadLog';
import { signWebhookBody, TIMESTAMP_TOLERANCE_MS } from '../webhooks/webhookVerify';
import {
  backoffMs,
  MAX_ATTEMPTS,
  REQUEST_TIMEOUT_MS,
  sendTestDelivery,
} from '../webhooks/dispatcher';
import {
  buildVerificationBody,
  challengeMatches,
  generateVerificationToken,
  hashVerificationToken,
  VERIFICATION_TOKEN_TTL_MS,
} from '../webhooks/verification';

export const webhooksRouter = Router();

// Apply API key authentication to every route on this router (#478).
// apiKeyAuth populates req.apiKey; requireApiKey enforces its presence.
webhooksRouter.use(apiKeyAuth, requireApiKey);

// Audit GET access to webhook config — webhook secrets are sensitive (#890)
webhooksRouter.use(sensitiveReadLog('webhook_read', (req) => req.path));

// Secret must be at least 32 characters to carry sufficient HMAC entropy (#481).
const MIN_SECRET_LENGTH = 32;

// Placeholder address used in preview/ping payloads when the subscription does
// not filter on a specific contract.
const SAMPLE_CONTRACT_ADDRESS = `C${'A'.repeat(55)}`;

const createSchema = z.object({
  url: z.string().url(),
  secret: z.string().min(MIN_SECRET_LENGTH).optional(),
  contractAddress: z.string().optional(),
  eventType: z.string().optional(),
  topicSymbol: z.string().optional(),
});

// Update accepts any subset of mutable fields. `null` clears a filter.
const updateSchema = z
  .object({
    url: z.string().url().optional(),
    contractAddress: z.string().nullable().optional(),
    eventType: z.string().nullable().optional(),
    topicSymbol: z.string().nullable().optional(),
    active: z.boolean().optional(),
  })
  .refine((data) => Object.keys(data).length > 0, {
    message: 'At least one updatable field must be provided',
  });

type SubFilter = {
  contractAddress: string | null;
  eventType: string | null;
  topicSymbol: string | null;
};

/**
 * Build a synthetic, serialisable event that mirrors the real delivery
 * envelope for the given subscription filters. Used by the preview and ping
 * endpoints so owners can validate their integration without waiting for
 * on-chain activity.
 */
function buildSampleEvent(sub: SubFilter): Record<string, unknown> {
  return {
    id: `evt_test_${uuidv7()}`,
    contractAddress: sub.contractAddress ?? SAMPLE_CONTRACT_ADDRESS,
    eventType: sub.eventType ?? 'transfer',
    topicSymbol: sub.topicSymbol ?? 'TEST',
    decoded: {
      test: true,
      note: 'Synthetic payload generated by the webhook preview/ping endpoints',
    },
    ledgerSequence: 0,
    ledgerCloseTime: new Date().toISOString(),
    transactionHash: '0'.repeat(64),
  };
}

/**
 * @swagger
 * /webhooks:
 *   post:
 *     summary: Register a webhook subscription
 *     description: >
 *       Register a server endpoint to receive on-chain contract event
 *       notifications. Each delivery is signed with HMAC-SHA256 using the
 *       signing secret (X-Webhook-Signature header). Failed deliveries are
 *       retried with exponential backoff (up to 5 attempts).
 *       The secret is returned only once in this response — store it securely.
 *       New subscriptions start unverified; complete
 *       `POST /webhooks/{id}/verify` to confirm ownership of the URL.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [url]
 *             properties:
 *               url:
 *                 type: string
 *                 format: uri
 *                 description: HTTPS endpoint to receive webhook payloads
 *               secret:
 *                 type: string
 *                 minLength: 32
 *                 description: >
 *                   Optional signing secret (min 32 chars). If omitted a
 *                   256-bit random secret is generated for you. The value is
 *                   returned only once — it cannot be retrieved again.
 *               contractAddress:
 *                 type: string
 *                 description: Filter to a specific contract (omit for all contracts)
 *               eventType:
 *                 type: string
 *                 description: Filter to a specific event type (e.g. "transfer")
 *               topicSymbol:
 *                 type: string
 *                 description: Filter to a specific topic symbol
 *     responses:
 *       201:
 *         description: Subscription created — includes the signing secret (shown once)
 *       400:
 *         description: Validation error
 *       401:
 *         description: API key required
 */
webhooksRouter.post(
  '/',
  asyncHandler(async (req: Request, res: Response) => {
    const parsed = createSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

    // SSRF guard: reject URLs that resolve to private/loopback/metadata addresses.
    try {
      await assertSafeUrl(parsed.data.url);
    } catch (err) {
      const message = err instanceof SsrfBlockedError ? err.message : 'Invalid webhook URL';
      return res.status(400).json({ error: message });
    }

    // Generate a high-entropy secret when the caller doesn't supply one (#481).
    const secret = parsed.data.secret ?? crypto.randomBytes(32).toString('hex');

    const sub = await prisma.webhookSubscription.create({
      data: {
        id: uuidv7(),
        apiKeyId: req.apiKey!.id,
        url: parsed.data.url,
        secret,
        contractAddress: parsed.data.contractAddress,
        eventType: parsed.data.eventType,
        topicSymbol: parsed.data.topicSymbol,
      },
    });

    // Return the secret only at creation time (#481).
    res.status(201).json({
      id: sub.id,
      url: sub.url,
      secret,
      contractAddress: sub.contractAddress,
      eventType: sub.eventType,
      topicSymbol: sub.topicSymbol,
      active: sub.active,
      verified: sub.verified,
      createdAt: sub.createdAt,
    });
  }),
);

/**
 * @swagger
 * /webhooks:
 *   get:
 *     summary: List webhook subscriptions owned by the caller
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     responses:
 *       200:
 *         description: List of subscriptions (secrets omitted)
 *       401:
 *         description: API key required
 */
webhooksRouter.get(
  '/',
  asyncHandler(async (req: Request, res: Response) => {
    const subs = await prismaRead.webhookSubscription.findMany({
      where: { apiKeyId: req.apiKey!.id },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        url: true,
        contractAddress: true,
        eventType: true,
        topicSymbol: true,
        active: true,
        verified: true,
        verifiedAt: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    res.json({ data: subs });
  }),
);

/**
 * @swagger
 * /webhooks/sdk:
 *   get:
 *     summary: Integration guide for consuming webhook deliveries
 *     description: >
 *       Returns the delivery envelope, signing headers, retry policy, replay
 *       protection window, and copy-paste signature-verification snippets for
 *       common languages.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     responses:
 *       200:
 *         description: SDK / integration guidance
 */
webhooksRouter.get(
  '/sdk',
  asyncHandler(async (_req: Request, res: Response) => {
    res.json({
      version: '1.0',
      envelope: {
        method: 'POST',
        contentType: 'application/json',
        body: {
          event: {
            id: 'string',
            contractAddress: 'string',
            eventType: 'string',
            topicSymbol: 'string | null',
            decoded: 'object',
            ledgerSequence: 'number',
            ledgerCloseTime: 'ISO-8601 string',
            transactionHash: 'string',
          },
          attempt: 'number (1-based)',
        },
      },
      headers: {
        'X-Webhook-Signature':
          'sha256=<hex HMAC-SHA256 of the raw request body, keyed by your signing secret>',
        'X-Webhook-Timestamp': 'unix epoch milliseconds',
      },
      verification: {
        algorithm: 'HMAC-SHA256',
        signedPayload: 'the raw request body bytes (JSON string), exactly as received',
        headerFormat: 'sha256=<hex>',
        timestampHeader: 'X-Webhook-Timestamp',
        toleranceMs: TIMESTAMP_TOLERANCE_MS,
        replayProtection:
          'Reject requests whose X-Webhook-Timestamp is outside the tolerance window and cache accepted signatures for the window to reject replays.',
      },
      retryPolicy: {
        maxAttempts: MAX_ATTEMPTS,
        backoffMs: [1, 2, 3, 4].map((attempt) => backoffMs(attempt)),
        requestTimeoutMs: REQUEST_TIMEOUT_MS,
        successCriteria: 'HTTP 2xx',
      },
      endpoints: {
        create: 'POST /webhooks',
        list: 'GET /webhooks',
        update: 'PATCH /webhooks/:id',
        delete: 'DELETE /webhooks/:id',
        verify: 'POST /webhooks/:id/verify',
        ping: 'POST /webhooks/:id/ping',
        preview: 'GET /webhooks/:id/preview',
        deliveries: 'GET /webhooks/:id/deliveries',
      },
      snippets: {
        typescript: `import crypto from 'crypto';

export function verifyWebhook(rawBody: Buffer, secret: string, signature: string, timestamp: string) {
  const ts = Number(timestamp);
  if (!Number.isFinite(ts) || Math.abs(Date.now() - ts) > ${TIMESTAMP_TOLERANCE_MS}) {
    throw new Error('Timestamp outside tolerance window');
  }

  const expected = 'sha256=' + crypto.createHmac('sha256', secret).update(rawBody).digest('hex');
  const a = Buffer.from(expected);
  const b = Buffer.from(signature);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
    throw new Error('Invalid signature');
  }
}`,
        python: `import hmac, hashlib, time

def verify_webhook(raw_body: bytes, secret: str, signature: str, timestamp: str, tolerance_ms: int = ${TIMESTAMP_TOLERANCE_MS}) -> bool:
    ts = int(timestamp)
    if abs(time.time() * 1000 - ts) > tolerance_ms:
        raise ValueError("Timestamp outside tolerance window")

    expected = "sha256=" + hmac.new(secret.encode(), raw_body, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(expected, signature):
        raise ValueError("Invalid signature")
    return True`,
        go: `package webhook

import (
    "crypto/hmac"
    "crypto/sha256"
    "encoding/hex"
    "fmt"
)

func Verify(rawBody []byte, secret, signature string) error {
    mac := hmac.New(sha256.New, []byte(secret))
    mac.Write(rawBody)
    expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))
    if !hmac.Equal([]byte(expected), []byte(signature)) {
        return fmt.Errorf("invalid signature")
    }
    return nil
}`,
        curl: `# Verify the handshake challenge (response must echo it back)
curl -X POST https://api.example.com/webhooks/$SUB_ID/verify \\
  -H "X-Api-Key: $SOROBAN_API_KEY"

# Send yourself a synthetic event
curl -X POST https://api.example.com/webhooks/$SUB_ID/ping \\
  -H "X-Api-Key: $SOROBAN_API_KEY"

# Inspect the exact body + headers before writing receiver code
curl https://api.example.com/webhooks/$SUB_ID/preview \\
  -H "X-Api-Key: $SOROBAN_API_KEY"`,
      },
      verificationHandshake: {
        request:
          'POST {url} signed like a delivery, body {"type":"webhook.verification","subscriptionId","challenge","timestamp"}',
        response:
          'Return HTTP 2xx with {"challenge":"<value you received>"} (or the value as plain text) to complete verification.',
        ttlMs: VERIFICATION_TOKEN_TTL_MS,
      },
    });
  }),
);

/**
 * @swagger
 * /webhooks/{id}:
 *   patch:
 *     summary: Update a webhook subscription
 *     description: >
 *       Update the destination URL, event filters, or active state. Changing
 *       the URL resets verification — re-run `POST /webhooks/{id}/verify`.
 *       Deactivating a subscription immediately cancels pending deliveries.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               url: { type: string, format: uri }
 *               contractAddress: { type: string, nullable: true }
 *               eventType: { type: string, nullable: true }
 *               topicSymbol: { type: string, nullable: true }
 *               active: { type: boolean }
 *     responses:
 *       200:
 *         description: Updated subscription
 *       400:
 *         description: Validation error or blocked URL
 *       404:
 *         description: Not found or not owned by caller
 *       401:
 *         description: API key required
 */
webhooksRouter.patch(
  '/:id',
  asyncHandler(async (req: Request, res: Response) => {
    const parsed = updateSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

    const existing = await prismaRead.webhookSubscription.findFirst({
      where: { id: req.params.id, apiKeyId: req.apiKey!.id },
    });
    if (!existing) return res.status(404).json({ error: 'Subscription not found' });

    const data: Prisma.WebhookSubscriptionUpdateInput = {};

    if (parsed.data.url !== undefined && parsed.data.url !== existing.url) {
      try {
        await assertSafeUrl(parsed.data.url);
      } catch (err) {
        const message = err instanceof SsrfBlockedError ? err.message : 'Invalid webhook URL';
        return res.status(400).json({ error: message });
      }
      data.url = parsed.data.url;
      // A new destination has not completed the handshake — reset verification.
      data.verified = false;
      data.verifiedAt = null;
      data.verificationToken = null;
      data.verificationExpiresAt = null;
    }

    if (parsed.data.contractAddress !== undefined) {
      data.contractAddress = parsed.data.contractAddress ?? null;
    }
    if (parsed.data.eventType !== undefined) {
      data.eventType = parsed.data.eventType ?? null;
    }
    if (parsed.data.topicSymbol !== undefined) {
      data.topicSymbol = parsed.data.topicSymbol ?? null;
    }
    if (parsed.data.active !== undefined) {
      data.active = parsed.data.active;
    }

    const sub = await prisma.webhookSubscription.update({
      where: { id: existing.id },
      data,
    });

    // When deactivating, immediately cancel all pending deliveries so the
    // retry loop doesn't attempt them before it notices the subscription is
    // inactive (#482).
    if (parsed.data.active === false) {
      await prisma.webhookDelivery.updateMany({
        where: { subscriptionId: sub.id, status: 'pending' },
        data: {
          status: 'cancelled',
          processingStatus: 'done',
          leaseExpiresAt: null,
          nextRetryAt: null,
        },
      });
    }

    res.json({
      id: sub.id,
      url: sub.url,
      contractAddress: sub.contractAddress,
      eventType: sub.eventType,
      topicSymbol: sub.topicSymbol,
      active: sub.active,
      verified: sub.verified,
      verifiedAt: sub.verifiedAt,
      updatedAt: sub.updatedAt,
    });
  }),
);

/**
 * @swagger
 * /webhooks/{id}:
 *   delete:
 *     summary: Delete a webhook subscription
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       204:
 *         description: Deleted
 *       404:
 *         description: Not found or not owned by caller
 *       401:
 *         description: API key required
 */
webhooksRouter.delete(
  '/:id',
  asyncHandler(async (req: Request, res: Response) => {
    try {
      await prisma.webhookSubscription.delete({
        where: { id: req.params.id, apiKeyId: req.apiKey!.id },
      });
      res.status(204).end();
    } catch {
      res.status(404).json({ error: 'Subscription not found' });
    }
  }),
);

/**
 * @swagger
 * /webhooks/{id}/verify:
 *   post:
 *     summary: Verify ownership of a subscription's destination URL
 *     description: >
 *       Challenge/response handshake. The server sends a signed verification
 *       request containing a random `challenge` to the subscription URL. The
 *       endpoint must reply with HTTP 2xx and echo the challenge back as
 *       `{"challenge":"<value>"}` (plain-text echo is also accepted). On
 *       success the subscription is marked verified.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       200:
 *         description: Subscription verified
 *       400:
 *         description: URL blocked, or the endpoint did not echo the challenge
 *       404:
 *         description: Not found or not owned by caller
 *       502:
 *         description: Destination unreachable or returned a non-2xx status
 *       401:
 *         description: API key required
 */
webhooksRouter.post(
  '/:id/verify',
  asyncHandler(async (req: Request, res: Response) => {
    const sub = await prismaRead.webhookSubscription.findFirst({
      where: { id: req.params.id, apiKeyId: req.apiKey!.id },
    });
    if (!sub) return res.status(404).json({ error: 'Subscription not found' });

    const challenge = generateVerificationToken();
    const body = buildVerificationBody(sub.id, challenge);
    const timestampMs = Date.now();

    // Persist only the digest of the challenge, with an expiry.
    await prisma.webhookSubscription.update({
      where: { id: sub.id },
      data: {
        verificationToken: hashVerificationToken(challenge),
        verificationExpiresAt: new Date(Date.now() + VERIFICATION_TOKEN_TTL_MS),
      },
    });

    const startMs = Date.now();
    try {
      const response = await safePost(
        sub.url,
        body,
        {
          'Content-Type': 'application/json',
          'X-Webhook-Timestamp': String(timestampMs),
          'X-Webhook-Signature': signWebhookBody(body, sub.secret),
        },
        REQUEST_TIMEOUT_MS,
      );
      const durationMs = Date.now() - startMs;

      if (response.status < 200 || response.status >= 300) {
        return res.status(502).json({
          verified: false,
          statusCode: response.status,
          durationMs,
          error: `Endpoint responded with HTTP ${response.status}`,
        });
      }

      if (!challengeMatches(response.data, challenge)) {
        return res.status(400).json({
          verified: false,
          statusCode: response.status,
          durationMs,
          error:
            'Endpoint did not echo the challenge. Respond with {"challenge":"<value>"} to complete verification.',
        });
      }

      const verifiedAt = new Date();
      await prisma.webhookSubscription.update({
        where: { id: sub.id },
        data: {
          verified: true,
          verifiedAt,
          verificationToken: null,
          verificationExpiresAt: null,
        },
      });

      return res.json({
        verified: true,
        subscriptionId: sub.id,
        verifiedAt,
        statusCode: response.status,
        durationMs,
      });
    } catch (err) {
      const durationMs = Date.now() - startMs;
      const blocked = err instanceof SsrfBlockedError;
      return res.status(blocked ? 400 : 502).json({
        verified: false,
        durationMs,
        error: blocked ? (err as Error).message : 'Verification request to the destination failed',
      });
    }
  }),
);

/**
 * @swagger
 * /webhooks/{id}/ping:
 *   post:
 *     summary: Send a synthetic test event to a subscription
 *     description: >
 *       Delivers a signed sample event to the subscription URL and records the
 *       attempt as a delivery. No retry is scheduled — this is a one-shot
 *       connectivity/signature test. The URL is SSRF-validated first.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       200:
 *         description: Attempt completed (check `success`)
 *       400:
 *         description: Destination URL blocked by the SSRF guard
 *       404:
 *         description: Not found or not owned by caller
 *       401:
 *         description: API key required
 */
webhooksRouter.post(
  '/:id/ping',
  asyncHandler(async (req: Request, res: Response) => {
    const sub = await prismaRead.webhookSubscription.findFirst({
      where: { id: req.params.id, apiKeyId: req.apiKey!.id },
    });
    if (!sub) return res.status(404).json({ error: 'Subscription not found' });

    const result = await sendTestDelivery({
      subscriptionId: sub.id,
      url: sub.url,
      secret: sub.secret,
      payload: buildSampleEvent(sub),
      storeResponseBody: sub.storeResponseBody,
      responseRetentionDays: sub.responseRetentionDays,
    });

    res.status(result.blocked ? 400 : 200).json({ subscriptionId: sub.id, ...result });
  }),
);

/**
 * @swagger
 * /webhooks/{id}/preview:
 *   get:
 *     summary: Preview the exact payload and headers for a subscription
 *     description: >
 *       Returns the synthetic event envelope that a delivery would send, along
 *       with the signing headers (including a real signature computed with the
 *       subscription's secret for the sample body) so owners can test their
 *       verification code before going live.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       200:
 *         description: Sample delivery envelope
 *       404:
 *         description: Not found or not owned by caller
 *       401:
 *         description: API key required
 */
webhooksRouter.get(
  '/:id/preview',
  asyncHandler(async (req: Request, res: Response) => {
    const sub = await prismaRead.webhookSubscription.findFirst({
      where: { id: req.params.id, apiKeyId: req.apiKey!.id },
    });
    if (!sub) return res.status(404).json({ error: 'Subscription not found' });

    const event = buildSampleEvent(sub);
    const rawBody = JSON.stringify({ event, attempt: 1 });
    const timestampMs = Date.now();

    res.json({
      subscriptionId: sub.id,
      delivery: {
        method: 'POST',
        url: sub.url,
        headers: {
          'Content-Type': 'application/json',
          'X-Webhook-Timestamp': String(timestampMs),
          'X-Webhook-Signature': signWebhookBody(rawBody, sub.secret),
        },
        body: { event, attempt: 1 },
      },
      rawBody,
      signatureFormat: 'sha256=<hex>',
      note: 'The signature is computed over rawBody. Verification snippets: GET /webhooks/sdk',
    });
  }),
);

/**
 * @swagger
 * /webhooks/{id}/deliveries:
 *   get:
 *     summary: Get delivery history for a webhook subscription
 *     description: Returns the last 50 delivery attempts including status, HTTP response, and retry schedule.
 *     security:
 *       - ApiKeyAuth: []
 *     tags: [Webhooks]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *     responses:
 *       200:
 *         description: Delivery history
 *       404:
 *         description: Subscription not found or not owned by caller
 *       401:
 *         description: API key required
 */
webhooksRouter.get(
  '/:id/deliveries',
  asyncHandler(async (req: Request, res: Response) => {
    // Verify ownership before returning delivery history (#478).
    const sub = await prismaRead.webhookSubscription.findFirst({
      where: { id: req.params.id, apiKeyId: req.apiKey!.id },
      select: { id: true },
    });
    if (!sub) return res.status(404).json({ error: 'Subscription not found' });

    const deliveries = await prismaRead.webhookDelivery.findMany({
      where: { subscriptionId: sub.id },
      orderBy: { createdAt: 'desc' },
      take: 50,
    });
    res.json({ data: deliveries });
  }),
);
