-- Phase 2 of issue #734 (docs/adr/005): move the id default off the database
-- and into application code (uuidv7(), src/utils/uuidv7.ts). Existing rows
-- keep their CUID values unchanged; only newly inserted rows get UUIDv7 ids.
--
-- NOTE: hand-authored, not generated by `prisma migrate dev` (no local
-- `npm install` was run for this contribution). Please verify against a real
-- migration diff/CI before merging.

ALTER TABLE "_audit_logs" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "_webhook_deliveries" ALTER COLUMN "id" DROP DEFAULT;
