# AUTO-GENERATED by `npm run sdk:generate` from the OpenAPI spec served at
# /api/v1/openapi.json. DO NOT EDIT: CI regenerates this file and fails on drift.
"""Typed models for API payloads (TypedDicts; all keys optional)."""

from typing import Dict, List, Literal, Optional, TypedDict, Union

__all__ = ["AnonymitySetSnapshot", "Contract", "CronExecution", "CronJob", "DeAnonymizationFinding", "Error", "Event", "FuzzFinding", "FuzzRun", "GovernanceTimelock", "LeaderboardEntry", "MevAlert", "MevAttacker", "MevEvent", "MevOverview", "MevVictim", "OracleReputationResponse", "PrivacyAnalytics", "PrivacyComplianceReport", "PrivacyProtocolDetail", "PrivacyProtocolInfo", "PrivacyTransaction", "ProtocolMevResistance", "ReputationAttestationRecord", "ReputationBadge", "ReputationBreakdownItem", "ReputationChainScore", "ReputationDisputeRecord", "ReputationEndorsement", "ReputationLinkedIdentity", "ReputationNftRecord", "ReputationProfileRecord", "ReputationProof", "ReputationScoreResult", "ReputationVerifiableCredential", "RevertAnalysis", "SandboxAccount", "SandboxCallResult", "SandboxCiResult", "SandboxContract", "SandboxOptimizeResult", "SandboxSession", "SandboxShare", "SandboxSnapshot", "SandboxTemplate", "SandboxTemplateParams", "SandboxVerifyResult", "ScheduledOperation", "SimulationTrace", "StorageEfficiencyLog", "SybilAssessment", "ThreatAdvisory", "ThreatComment", "ThreatReview", "TimerAlert", "TipSubscription", "Token", "Transaction", "TrustPath", "VerifiedIdentityLink", "VestingSchedule", "VulnerabilitySource", "WebhookSubscription", "ZodFlattenedError", "ZodValidationError"]

AnonymitySetSnapshot = TypedDict(
    "AnonymitySetSnapshot",
    {
        "contractAddress": Optional[str],
        "effectiveSetSize": Optional[int],
        "id": str,
        "protocol": Literal["SHIELDED_TRANSFER", "ZK_SNARK", "ZK_STARK", "BULLETPROOF", "STEALTH_ADDRESS", "MIXER", "PRIVATE_VOTING", "OFF_CHAIN_DATA", "ENCRYPTED_STATE", "DIFFERENTIAL_PRIVACY"],
        "setSize": int,
        "timestamp": str,
    },
    total=False,
)

Contract = TypedDict(
    "Contract",
    {
        "abi": Optional[Dict[str, object]],
        "address": str,
        "createdAt": str,
        "description": Optional[str],
        "functionSignatures": Optional[List[Dict[str, object]]],
        "id": str,
        "isToken": bool,
        "isVerified": bool,
        "name": Optional[str],
        "tokenDecimals": Optional[int],
        "tokenName": Optional[str],
        "tokenSymbol": Optional[str],
        "updatedAt": str,
        "wasmHash": Optional[str],
    },
    total=False,
)

CronExecution = TypedDict(
    "CronExecution",
    {
        "cronJobId": str,
        "duration": Optional[int],
        "errorMessage": Optional[str],
        "executedAt": str,
        "gasUsed": Optional[int],
        "id": str,
        "success": bool,
        "txHash": Optional[str],
    },
    total=False,
)

CronJob = TypedDict(
    "CronJob",
    {
        "contractAddress": str,
        "createdAt": str,
        "createdBy": Optional[str],
        "cronExpression": str,
        "description": Optional[str],
        "enabled": bool,
        "failedRuns": int,
        "functionArgs": Dict[str, object],
        "functionName": str,
        "id": str,
        "lastRunAt": Optional[str],
        "maxRuns": Optional[int],
        "nextRunAt": Optional[str],
        "successfulRuns": int,
        "totalRuns": int,
    },
    total=False,
)

DeAnonymizationFinding = TypedDict(
    "DeAnonymizationFinding",
    {
        "confidence": float,
        "detectedAt": str,
        "evidence": Dict[str, object],
        "id": str,
        "linkedAddresses": List[str],
        "probability": Optional[float],
        "sourceTx": str,
        "targetAddress": str,
        "technique": str,
    },
    total=False,
)

Error = TypedDict(
    "Error",
    {
        "error": str,
    },
    total=False,
)

Event = TypedDict(
    "Event",
    {
        "compacted": bool,
        "contractAddress": str,
        "createdAt": str,
        "data": Dict[str, object],
        "decoded": Optional[Dict[str, object]],
        "eventType": str,
        "id": str,
        "ledgerCloseTime": str,
        "ledgerSequence": int,
        "topicSymbol": Optional[str],
        "topics": List[str],
        "transactionHash": str,
    },
    total=False,
)

FuzzFinding = TypedDict(
    "FuzzFinding",
    {
        "callSequence": List[Dict[str, object]],
        "createdAt": str,
        "description": str,
        "fuzzRunId": str,
        "id": str,
        "reproducible": bool,
        "severity": str,
        "stateDump": Dict[str, object],
        "title": str,
    },
    total=False,
)

FuzzRun = TypedDict(
    "FuzzRun",
    {
        "completedAt": Optional[str],
        "contractId": str,
        "id": str,
        "sessionId": str,
        "startedAt": str,
        "status": str,
        "strategies": List[Dict[str, object]],
        "totalIterations": int,
        "uniqueFindings": int,
    },
    total=False,
)

GovernanceTimelock = TypedDict(
    "GovernanceTimelock",
    {
        "calldatas": List[str],
        "cancelledBy": Optional[str],
        "contractAddress": str,
        "description": Optional[str],
        "executedTx": Optional[str],
        "executionTime": str,
        "executor": Optional[str],
        "expiryTime": Optional[str],
        "gracePeriod": Optional[int],
        "id": str,
        "minDelay": int,
        "operationHash": Optional[str],
        "proposalId": Optional[str],
        "proposer": str,
        "queuedAt": str,
        "status": str,
        "targets": List[str],
        "title": Optional[str],
        "values": List[str],
    },
    total=False,
)

LeaderboardEntry = TypedDict(
    "LeaderboardEntry",
    {
        "activeChains": int,
        "address": str,
        "badges": List[str],
        "linkedAddresses": List[str],
        "rank": int,
        "score": float,
        "sybilRisk": float,
    },
    total=False,
)

MevAlert = TypedDict(
    "MevAlert",
    {
        "acknowledged": bool,
        "alertType": Literal["sandwich_in_progress", "sandwich_detected", "mev_spike", "protocol_targeted", "user_victim"],
        "createdAt": str,
        "description": str,
        "estimatedLoss": Optional[float],
        "id": str,
        "protocolAddress": Optional[str],
        "recommendedAction": Optional[str],
        "resolvedAt": Optional[str],
        "severity": Literal["critical", "high", "medium", "low"],
        "title": str,
        "txHash": Optional[str],
        "victimAddress": Optional[str],
    },
    total=False,
)

MevAttacker = TypedDict(
    "MevAttacker",
    {
        "address": str,
        "attackCount": int,
        "createdAt": str,
        "favoriteType": Optional[Literal["sandwich", "flash_loan_attack", "backrunning", "displacement", "jit_liquidity", "cex_dex_arbitrage", "cross_dex_arbitrage", "liquidation", "nft_mev"]],
        "firstSeen": Optional[str],
        "id": str,
        "isContract": bool,
        "lastAttackAt": Optional[str],
        "tags": Optional[List[str]],
        "totalProfitUsd": float,
        "updatedAt": str,
    },
    total=False,
)

MevEvent = TypedDict(
    "MevEvent",
    {
        "amountIn": Optional[str],
        "amountOut": Optional[str],
        "attackerAddress": Optional[str],
        "confidence": float,
        "createdAt": str,
        "details": Optional[Dict[str, object]],
        "id": str,
        "ledgerSeq": int,
        "lossAmount": Optional[str],
        "lossUsd": Optional[float],
        "mevType": Literal["sandwich", "flash_loan_attack", "backrunning", "displacement", "jit_liquidity", "cex_dex_arbitrage", "cross_dex_arbitrage", "liquidation", "nft_mev"],
        "profitAmount": Optional[str],
        "profitUsd": Optional[float],
        "protocolAddress": Optional[str],
        "timestamp": str,
        "tokenIn": Optional[str],
        "tokenOut": Optional[str],
        "txHash": str,
        "txOrder": Optional[Dict[str, object]],
        "victimAddress": Optional[str],
    },
    total=False,
)

MevOverview = TypedDict(
    "MevOverview",
    {
        "byType": Dict[str, object],
        "recentEvents": List[Dict[str, object]],
        "topAttackers": List[Dict[str, object]],
        "topVictims": List[Dict[str, object]],
        "totalEvents": int,
        "totalLossUsd": float,
        "totalProfitUsd": float,
    },
    total=False,
)

MevVictim = TypedDict(
    "MevVictim",
    {
        "address": str,
        "createdAt": str,
        "firstIncidentAt": Optional[str],
        "id": str,
        "incidentCount": int,
        "lastIncidentAt": Optional[str],
        "protectionScore": Optional[float],
        "totalLossUsd": float,
        "updatedAt": str,
    },
    total=False,
)

OracleReputationResponse = TypedDict(
    "OracleReputationResponse",
    {
        "address": str,
        "attestations": List[Dict[str, object]],
        "badges": List["ReputationBadge"],
        "breakdown": List["ReputationBreakdownItem"],
        "credentials": List[Dict[str, object]],
        "proof": "ReputationProof",
        "score": float,
        "sybil": "SybilAssessment",
    },
    total=False,
)

PrivacyAnalytics = TypedDict(
    "PrivacyAnalytics",
    {
        "avgAnonymitySet": Optional[float],
        "avgPrivacyScore": Optional[float],
        "avgRiskScore": Optional[float],
        "byProtocol": Dict[str, object],
        "deAnonymizedCount": Optional[int],
        "id": str,
        "maxAnonymitySet": Optional[int],
        "medianAnonymitySet": Optional[float],
        "period": str,
        "privacyShare": float,
        "timestamp": str,
        "totalPrivateTx": int,
        "totalTx": int,
        "totalVolume": str,
        "uniqueContracts": Optional[int],
        "uniqueUsers": Optional[int],
        "volumeShare": Optional[float],
    },
    total=False,
)

PrivacyComplianceReport = TypedDict(
    "PrivacyComplianceReport",
    {
        "address": str,
        "complianceLabel": Optional[str],
        "flagReason": Optional[str],
        "flagged": bool,
        "id": str,
        "lastActivity": str,
        "linkedAddresses": List[str],
        "protocolsUsed": List[str],
        "reportGeneratedAt": str,
        "riskScore": Optional[float],
        "totalPrivateTx": int,
    },
    total=False,
)

PrivacyProtocolDetail = TypedDict(
    "PrivacyProtocolDetail",
    {
        "avgAnonymitySet": Optional[float],
        "cryptographicPrimitivesUsed": Optional[Dict[str, object]],
        "id": str,
        "period": str,
        "protocol": Literal["SHIELDED_TRANSFER", "ZK_SNARK", "ZK_STARK", "BULLETPROOF", "STEALTH_ADDRESS", "MIXER", "PRIVATE_VOTING", "OFF_CHAIN_DATA", "ENCRYPTED_STATE", "DIFFERENTIAL_PRIVACY"],
        "timestamp": str,
        "txCount": int,
        "uniqueContracts": Optional[int],
        "uniqueUsers": Optional[int],
        "volume": Optional[str],
    },
    total=False,
)

PrivacyProtocolInfo = TypedDict(
    "PrivacyProtocolInfo",
    {
        "category": str,
        "description": str,
        "name": str,
        "strength": int,
    },
    total=False,
)

PrivacyTransaction = TypedDict(
    "PrivacyTransaction",
    {
        "anonymitySetSize": Optional[int],
        "assetType": Optional[str],
        "contractAddresses": List[str],
        "cryptographicPrimitives": Optional[Dict[str, object]],
        "effectiveAnonymitySet": Optional[int],
        "guarantees": List[Literal["SENDER_PRIVACY", "RECIPIENT_PRIVACY", "AMOUNT_PRIVACY", "ASSET_TYPE_PRIVACY", "VOTE_PRIVACY", "FULL_PRIVACY"]],
        "id": str,
        "ledgerSequence": int,
        "participantCount": int,
        "participants": List[str],
        "privacyScore": Optional[float],
        "protocols": List[Literal["SHIELDED_TRANSFER", "ZK_SNARK", "ZK_STARK", "BULLETPROOF", "STEALTH_ADDRESS", "MIXER", "PRIVATE_VOTING", "OFF_CHAIN_DATA", "ENCRYPTED_STATE", "DIFFERENTIAL_PRIVACY"]],
        "riskScore": Optional[float],
        "timestamp": str,
        "totalValue": Optional[str],
        "txHash": str,
        "usdValue": Optional[float],
    },
    total=False,
)

ProtocolMevResistance = TypedDict(
    "ProtocolMevResistance",
    {
        "batchAuctions": bool,
        "commitReveal": bool,
        "contractAddress": str,
        "contractName": Optional[str],
        "createdAt": str,
        "encryptedTxs": bool,
        "id": str,
        "lastIncidentAt": Optional[str],
        "mevExtractedUsd": float,
        "privateMempool": bool,
        "recommendations": Optional[List[str]],
        "score": float,
        "scoreHistory": Optional[List[Dict[str, object]]],
        "slippageDefault": Optional[float],
        "totalIncidents": int,
        "updatedAt": str,
    },
    total=False,
)

ReputationAttestationRecord = TypedDict(
    "ReputationAttestationRecord",
    {
        "attester": str,
        "blockNumber": Optional[int],
        "chainId": str,
        "createdAt": str,
        "data": Optional[Dict[str, object]],
        "id": str,
        "profileId": str,
        "recipient": Optional[str],
        "revoked": bool,
        "schemaId": str,
        "signature": Optional[str],
        "subject": str,
        "transactionHash": Optional[str],
        "uid": str,
        "updatedAt": str,
        "verificationMsg": Optional[str],
        "verified": bool,
    },
    total=False,
)

ReputationBadge = TypedDict(
    "ReputationBadge",
    {
        "criteria": str,
        "description": str,
        "earnedAt": Optional[str],
        "id": str,
        "name": str,
        "verifiable": bool,
    },
    total=False,
)

ReputationBreakdownItem = TypedDict(
    "ReputationBreakdownItem",
    {
        "category": str,
        "evidence": str,
        "maxPoints": float,
        "points": float,
        "signal": str,
    },
    total=False,
)

ReputationChainScore = TypedDict(
    "ReputationChainScore",
    {
        "address": str,
        "breakdown": List["ReputationBreakdownItem"],
        "chainId": str,
        "score": float,
    },
    total=False,
)

ReputationDisputeRecord = TypedDict(
    "ReputationDisputeRecord",
    {
        "challenge": Optional[str],
        "challenger": str,
        "createdAt": str,
        "evidenceHash": Optional[str],
        "id": str,
        "outcome": Optional[Literal["upheld", "rejected", "timeout"]],
        "profileId": str,
        "quorumVotes": Optional[int],
        "resolvedAt": Optional[str],
        "respondent": str,
        "status": Literal["open", "resolved"],
        "updatedAt": str,
        "votes": List[Dict[str, object]],
    },
    total=False,
)

ReputationEndorsement = TypedDict(
    "ReputationEndorsement",
    {
        "chainId": str,
        "createdAt": str,
        "endorser": str,
        "id": str,
        "profileId": str,
        "subject": str,
        "timestamp": Optional[str],
        "transactionHash": Optional[str],
        "weight": Optional[float],
    },
    total=False,
)

ReputationLinkedIdentity = TypedDict(
    "ReputationLinkedIdentity",
    {
        "address": str,
        "chainId": str,
        "createdAt": str,
        "id": str,
        "lastVerified": Optional[str],
        "metadata": Optional[Dict[str, object]],
        "profileId": str,
        "updatedAt": str,
        "verified": bool,
    },
    total=False,
)

ReputationNftRecord = TypedDict(
    "ReputationNftRecord",
    {
        "address": str,
        "badgeType": str,
        "createdAt": str,
        "id": str,
        "mintedTxHash": Optional[str],
        "tokenId": Optional[str],
    },
    total=False,
)

ReputationProfileRecord = TypedDict(
    "ReputationProfileRecord",
    {
        "address": str,
        "badgeIds": List[str],
        "categories": List[str],
        "categoryScores": Optional[Dict[str, object]],
        "chain": Optional[str],
        "combinedScore": Optional[float],
        "createdAt": str,
        "ethScore": Optional[float],
        "id": str,
        "lastUpdated": Optional[str],
        "signalBreakdown": Optional[Dict[str, object]],
        "solScore": Optional[float],
        "sorobanScore": Optional[float],
        "stellarScore": Optional[float],
        "updatedAt": str,
    },
    total=False,
)

ReputationProof = TypedDict(
    "ReputationProof",
    {
        "address": str,
        "algorithmVersion": str,
        "badgeHash": str,
        "breakdownHash": str,
        "chainIds": List[str],
        "inputHash": str,
        "linkedAddresses": List[str],
        "score": float,
    },
    total=False,
)

ReputationScoreResult = TypedDict(
    "ReputationScoreResult",
    {
        "activeChains": List[str],
        "address": str,
        "badges": List["ReputationBadge"],
        "breakdown": List["ReputationBreakdownItem"],
        "chainScores": List["ReputationChainScore"],
        "linkedAddresses": List[str],
        "proof": "ReputationProof",
        "rankCategory": str,
        "score": float,
        "sybil": "SybilAssessment",
    },
    total=False,
)

ReputationVerifiableCredential = TypedDict(
    "ReputationVerifiableCredential",
    {
        "context": Optional[str],
        "createdAt": str,
        "credentialId": str,
        "expirationDate": Optional[str],
        "id": str,
        "issuanceDate": Optional[str],
        "issuer": Optional[str],
        "profileId": str,
        "proofCreated": Optional[str],
        "proofPurpose": Optional[str],
        "proofType": Optional[str],
        "proofValue": Optional[str],
        "subjectData": Optional[Dict[str, object]],
        "subjectId": Optional[str],
        "type": Optional[str],
        "verificationMethod": Optional[str],
    },
    total=False,
)

RevertAnalysis = TypedDict(
    "RevertAnalysis",
    {
        "callStack": List[Dict[str, object]],
        "detail": Optional[str],
        "errorType": Literal["panic", "contract_error", "resource_limit", "auth_error", "wasm_error", "storage_error", "unknown"],
        "message": str,
        "suggestedFixes": List[str],
    },
    total=False,
)

SandboxAccount = TypedDict(
    "SandboxAccount",
    {
        "balance": str,
        "isPreFunded": bool,
        "label": Optional[str],
        "publicKey": str,
        "sequenceNumber": int,
    },
    total=False,
)

SandboxCallResult = TypedDict(
    "SandboxCallResult",
    {
        "callId": Optional[str],
        "error": Optional[str],
        "events": List[Dict[str, object]],
        "metrics": Optional[Dict[str, object]],
        "result": object,
        "stateAfter": Dict[str, object],
        "stateBefore": Dict[str, object],
        "success": bool,
        "trace": List[Dict[str, object]],
    },
    total=False,
)

SandboxCiResult = TypedDict(
    "SandboxCiResult",
    {
        "failure": Optional[str],
        "logs": List[Dict[str, object]],
        "passed": bool,
        "results": List[Dict[str, object]],
        "runId": str,
    },
    total=False,
)

SandboxContract = TypedDict(
    "SandboxContract",
    {
        "abi": Dict[str, object],
        "contractId": str,
        "deployedAt": str,
        "deployerAccount": str,
        "lastCalledAt": Optional[str],
        "name": Optional[str],
        "sourceContract": Optional[str],
        "state": Dict[str, object],
        "templateId": Optional[str],
        "totalCalls": int,
        "wasmHash": str,
    },
    total=False,
)

SandboxOptimizeResult = TypedDict(
    "SandboxOptimizeResult",
    {
        "hotPaths": List[str],
        "recommendations": List[Dict[str, object]],
        "totalEstimatedSavings": str,
    },
    total=False,
)

SandboxSession = TypedDict(
    "SandboxSession",
    {
        "accountCount": int,
        "callCount": int,
        "contractCount": int,
        "createdAt": str,
        "expiresAt": str,
        "id": str,
        "lastAccessed": str,
        "ledgerSequence": int,
        "ledgerTimestamp": str,
        "networkPassphrase": str,
        "snapshotCount": int,
        "status": str,
    },
    total=False,
)

SandboxShare = TypedDict(
    "SandboxShare",
    {
        "createdAt": str,
        "expiresAt": Optional[str],
        "id": str,
        "sessionId": str,
        "shareId": str,
        "snapshotState": Dict[str, object],
        "viewOnly": bool,
    },
    total=False,
)

SandboxSnapshot = TypedDict(
    "SandboxSnapshot",
    {
        "createdAt": str,
        "id": str,
        "name": str,
        "sessionId": str,
        "state": Dict[str, object],
    },
    total=False,
)

SandboxTemplate = TypedDict(
    "SandboxTemplate",
    {
        "abi": Dict[str, object],
        "author": str,
        "category": str,
        "defaultArgs": Dict[str, object],
        "deploymentGuide": str,
        "description": str,
        "id": str,
        "name": str,
        "version": str,
        "wasmBase64": str,
    },
    total=False,
)

SandboxTemplateParams = TypedDict(
    "SandboxTemplateParams",
    {
        "abi": Dict[str, object],
        "category": str,
        "deploymentGuide": str,
        "parameters": Dict[str, object],
        "templateId": str,
    },
    total=False,
)

SandboxVerifyResult = TypedDict(
    "SandboxVerifyResult",
    {
        "bound": Optional[Dict[str, object]],
        "checker": str,
        "counterexample": Optional[Dict[str, object]],
        "invariant": str,
        "passed": bool,
    },
    total=False,
)

ScheduledOperation = TypedDict(
    "ScheduledOperation",
    {
        "contractAddress": str,
        "createdBy": Optional[str],
        "description": Optional[str],
        "detectedAt": str,
        "eventsExecuted": int,
        "functionName": str,
        "id": str,
        "intervalSeconds": Optional[int],
        "lastExecutedAt": Optional[str],
        "nextTriggerAt": Optional[str],
        "parameters": Optional[Dict[str, object]],
        "recurrenceCount": Optional[int],
        "sourceTx": Optional[str],
        "status": Literal["PENDING", "ACTIVE", "EXECUTED", "EXPIRED", "CANCELLED", "FAILED"],
        "timerType": Literal["TIMELOCK", "VESTING", "DEADLINE", "COOLDOWN", "RECURRING", "TIME_WEIGHTED", "MULTI_STAGE", "ABSOLUTE"],
        "triggerTime": str,
        "windowEnd": Optional[str],
        "windowStart": Optional[str],
    },
    total=False,
)

SimulationTrace = TypedDict(
    "SimulationTrace",
    {
        "callGraph": Dict[str, object],
        "error": Optional[str],
        "events": List[Dict[str, object]],
        "steps": List[Dict[str, object]],
        "success": bool,
        "totalGas": int,
        "totalMemory": int,
    },
    total=False,
)

StorageEfficiencyLog = TypedDict(
    "StorageEfficiencyLog",
    {
        "actualReadBytes": int,
        "actualWriteBytes": int,
        "contractAddress": Optional[str],
        "efficiencyPct": float,
        "footprintBytes": int,
        "ledgerSequence": int,
        "readOnlyKeys": int,
        "readWriteKeys": int,
        "transactionHash": str,
        "unusedBytes": int,
    },
    total=False,
)

SybilAssessment = TypedDict(
    "SybilAssessment",
    {
        "address": str,
        "cluster": Optional[str],
        "confidence": float,
        "isSuspicious": bool,
        "reasons": List[str],
        "risk": float,
    },
    total=False,
)

ThreatAdvisory = TypedDict(
    "ThreatAdvisory",
    {
        "affectedChains": List[str],
        "affectedContracts": List[str],
        "createdAt": str,
        "cveId": Optional[str],
        "cvssScore": Optional[float],
        "description": Optional[str],
        "externalUrl": Optional[str],
        "ghsaId": Optional[str],
        "id": str,
        "mitigations": Optional[str],
        "publishedAt": Optional[str],
        "severity": Literal["critical", "high", "medium", "low", "info"],
        "sourceId": Optional[str],
        "status": Literal["open", "under_review", "resolved", "disputed"],
        "tags": List[str],
        "title": str,
        "updatedAt": str,
    },
    total=False,
)

ThreatComment = TypedDict(
    "ThreatComment",
    {
        "advisoryId": str,
        "authorKey": str,
        "body": str,
        "createdAt": str,
        "id": str,
    },
    total=False,
)

ThreatReview = TypedDict(
    "ThreatReview",
    {
        "advisoryId": str,
        "createdAt": str,
        "decision": Optional[Literal["approve", "reject", "escalate"]],
        "id": str,
        "notes": Optional[str],
        "reviewerKey": str,
        "role": Optional[Literal["analyst", "admin"]],
    },
    total=False,
)

TimerAlert = TypedDict(
    "TimerAlert",
    {
        "acknowledged": bool,
        "alertType": str,
        "delivered": bool,
        "id": str,
        "message": str,
        "scheduledOpId": Optional[str],
        "severity": str,
        "title": str,
        "triggerTime": str,
    },
    total=False,
)

TipSubscription = TypedDict(
    "TipSubscription",
    {
        "active": bool,
        "channel": Literal["email", "slack", "discord", "telegram"],
        "createdAt": str,
        "filters": Optional[Dict[str, object]],
        "id": str,
        "target": str,
        "updatedAt": str,
    },
    total=False,
)

Token = TypedDict(
    "Token",
    {
        "address": str,
        "tokenDecimals": Optional[int],
        "tokenName": Optional[str],
        "tokenSymbol": Optional[str],
    },
    total=False,
)

Transaction = TypedDict(
    "Transaction",
    {
        "contractAddress": Optional[str],
        "failureReason": Optional[str],
        "feeCharged": Optional[str],
        "freezeViolation": bool,
        "functionArgs": Optional[Dict[str, object]],
        "functionName": Optional[str],
        "hash": str,
        "humanReadable": Optional[str],
        "ledgerCloseTime": str,
        "ledgerSequence": int,
        "sorobanResources": Optional[Dict[str, object]],
        "sourceAccount": str,
        "status": str,
    },
    total=False,
)

TrustPath = TypedDict(
    "TrustPath",
    {
        "chainIds": List[str],
        "distance": int,
        "from": str,
        "path": Optional[List[str]],
        "to": str,
    },
    total=False,
)

VerifiedIdentityLink = TypedDict(
    "VerifiedIdentityLink",
    {
        "address": str,
        "canonicalAddress": str,
        "chainId": str,
        "messageHash": str,
        "verified": bool,
    },
    total=False,
)

VestingSchedule = TypedDict(
    "VestingSchedule",
    {
        "amountPerPeriod": Optional[str],
        "beneficiary": str,
        "cliffAmount": Optional[str],
        "cliffDate": Optional[str],
        "contractAddress": str,
        "detectedAt": str,
        "endDate": str,
        "id": str,
        "nextUnlockAmount": Optional[str],
        "nextUnlockDate": Optional[str],
        "periodSeconds": Optional[int],
        "periodsTotal": Optional[int],
        "sourceTx": Optional[str],
        "startDate": str,
        "status": str,
        "tokenAddress": str,
        "tokenSymbol": Optional[str],
        "totalAmount": str,
        "totalClaimed": str,
        "totalUnlocked": str,
        "vestingType": str,
    },
    total=False,
)

VulnerabilitySource = TypedDict(
    "VulnerabilitySource",
    {
        "active": bool,
        "createdAt": str,
        "feedUrl": Optional[str],
        "id": str,
        "lastFetchAt": Optional[str],
        "name": str,
        "sourceType": str,
        "updatedAt": str,
    },
    total=False,
)

WebhookSubscription = TypedDict(
    "WebhookSubscription",
    {
        "active": bool,
        "contractAddress": Optional[str],
        "createdAt": str,
        "eventType": Optional[str],
        "id": str,
        "topicSymbol": Optional[str],
        "url": str,
    },
    total=False,
)

ZodFlattenedError = TypedDict(
    "ZodFlattenedError",
    {
        "error": Dict[str, object],
    },
    total=False,
)

ZodValidationError = TypedDict(
    "ZodValidationError",
    {
        "error": List[Dict[str, object]],
    },
    total=False,
)
